series: Intermediate C++
title: C++ Writing Files
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Basic usage of ofstream.
language: C++
tags:
  - Input
  - Core
extra_resources:
connections:
  - series: Intermediate C++
    title: C++ Reading Files